apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: enc4djaik-python
  janus-idp.io/tekton: enc4djaik-python
  backstage.io/kubernetes-id: enc4djaik-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: enc4djaik-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
